repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.3
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: 'v4.0.0-alpha.8'
  hooks:
  - id: prettier
    types_or: [css, javascript, scss]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  # ref: https://github.com/pre-commit/pre-commit-hooks#hooks-available
  hooks:
    # Autoformat: Makes sure files end in a newline and only a newline.
    - id: end-of-file-fixer
    # Lint: Check for files with names that would conflict on a
    # case-insensitive filesystem like MacOS HFS+ or Windows FAT.
    - id: check-case-conflict
    - id: trailing-whitespace
